# config.yaml 檔案內容 (Streamlit Authenticator 配置)
# 請將此內容儲存在您的專案根目錄下的 config.yaml 檔案中。

cookie:
  expiry_days: 30
  key: random_signature_key_for_cookie
  name: equipment_app_cookie

credentials:
  usernames:
    admin:
      email: admin@company.com
      name: 系統管理員
      password: $2b$12$R.S9d/Q1VvB2K8W7S7y/qON.wL7jE5X9K/t9eY0OQG.Q4/t6Xg/U.
    test_user:
      email: test@example.com
      name: 測試用戶
      password: $2b$12$R.S9d/Q1VvB2K8W7S7y/qON.wL7jE5X9K/t9eY0OQG.Q4/t6Xg/U.

# 注意：上面的密碼是 hash 過的，對應的明文密碼 (Password) 都是 123456。
