# config.yaml 檔案內容 (Streamlit Authenticator 配置)

cookie:
  expiry_days: 30
  # 替換為更長的隨機密鑰，確保符合 Streamlit Authenticator 的要求
  key: "a2pYQ1B1c2QyY0tHNUh0YVdnNlpJcFFmYndzM1U5Z08zY1h1Y2Y3V1h6bDFjQXVxWnl1MEdKcnY=" 
  name: equipment_app_cookie

credentials:
  usernames:
    admin:
      email: admin@company.com
      name: 系統管理員
      password: $2b$12$R.S9d/Q1VvB2K8W7S7y/qON.wL7jE5X9K/t9eY0OQG.Q4/t6Xg/U.
    test_user:
      email: test@example.com
      name: 測試用戶
      password: $2b$12$R.S9d/Q1VvB2K8W7S7y/qON.wL7jE5X9K/t9eY0OQG.Q4/t6Xg/U.
